name: Integration Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_CON: ${{ secrets.DB_CON }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run test:lib:backup
